version: "2"
services:
  cadvisor:
    build:
      context: .
    container_name: cadvisor_simulation
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=10.108.0.11:8086
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
